/*
 * LIN Core API
 * Signal Interaction and Notification
 *
 * This file is application specific and depends on LDF/NCF files
 * Generated by configuration tool C:\EVWS\_LIBRARY_PLATFORMS\library_platform_mulan2\bin\ldf_nodegen.exe (version 1.4.0)
 *
 * Copyright (C) 2007-2015 Melexis N.V.
 */

#include "lin_api.h"

/*
 * Declaration of the frame buffers: data (signals) buffer and flags buffer
 */
/*
 * Frame doorFrontLeft_status
 */
doorFrontLeft_status_data_t	volatile doorFrontLeft_status_data = { 0x00U, 0x7fU, 0xffU};
doorFrontLeft_status_flags_t	volatile doorFrontLeft_status_flags;

/*
 * Frame doorFrontLeft_feedback
 */
doorFrontLeft_feedback_data_t	volatile doorFrontLeft_feedback_data = { 0xffU, 0x00U, 0xffU, 0xffU};
doorFrontLeft_feedback_flags_t	volatile doorFrontLeft_feedback_flags;

/*
 * Frame doorFrontLeft_setBackLight
 */
doorFrontLeft_setBackLight_data_t	volatile doorFrontLeft_setBackLight_data;
doorFrontLeft_setBackLight_flags_t	volatile doorFrontLeft_setBackLight_flags;


/*
 *  typedef struct {
 *      void volatile *dataBuffer;    
 *      void volatile *flagsBuffer;    
 *      l_u16   dataBufferSize;  
 *      l_u8    flagsBufferSize; 
 *      l_u8    frame_type;
 *  } FrameDescBlock_type;
 *
 * Note that event-triggered frame has the same data (signal) buffer and flags buffer as
 * an associated unconditional frame. "Event triggered frames means the event triggered frame
 * header, it will therefore not contain any signals" [LIN spec]
 */

FrameDescBlock_type const frame_list[ML_NUMBER_OF_DYNAMIC_MESSAGES] = {  
							/* Message index / id: */
    { &doorFrontLeft_status_data,	&doorFrontLeft_status_flags,	2U,	1U, ML_UNCOND_FREE },	 /* 0x00 0x4051		*/
    { &doorFrontLeft_feedback_data,	&doorFrontLeft_feedback_flags,	4U,	1U, ML_UNCOND_ASSOCIATED },	 /* 0x01 0x40c1		*/
    { &doorFrontLeft_feedback_data,	&doorFrontLeft_feedback_flags,	4U,	1U, ML_EVENT_TRIGGERED },	 /* 0x02 0x40c0		*/
    { &doorFrontLeft_setBackLight_data,	&doorFrontLeft_setBackLight_flags,	2U,	1U, ML_UNCOND_FREE },	 /* 0x03 0x40d1		*/
};


#if LIN_VERSION == 20
/*
 * LIN 2.0 message identifier list
 */
const l_u16 MID_list[ML_NUMBER_OF_DYNAMIC_MESSAGES] = {
  0x4051U,
  0x40c1U,
  0x40c0U,
  0x40d1U
};
#endif /* LIN_VERSION == 20 */

#if defined(HAS_EVENT_TRIGGERED_FRAMES)
/*
 * List of associated frames.
 * For event triggered frame, index of associated unconditional frame (not used)
 * For unconditional frame, index of associated event-triggered frame, if any
 * Contains 0xFF if there is no associated frame for this index  
 */
const l_u8 associatedFrames[ML_NUMBER_OF_DYNAMIC_MESSAGES] = {
	0xffU	/* doorFrontLeft_status : none */,
	(l_u8)doorAll_feedback_idx	/* doorFrontLeft_feedback : doorAll_feedback */,
	0xffU	/* doorAll_feedback : none */,
	0xffU	/* doorFrontLeft_setBackLight : none */
};

/*
 * Contains 16 flags for 16 dynamic frames
 * When signal value is updated via xxx_wr_yyy() function
 * the flag is set for the frame carrying this signal
 */
volatile l_u16 frame_updated;
#endif /* HAS_EVENT_TRIGGERED_FRAMES */

/* EOF */
