@echo off

gmake -s clean 		EXAMPLE="AWDG_Test IO_EX1 IO_EX1_STANDALONE_LOADER LIN_EX1 LIN_Unique_Loader_NAD PWM_EX1 TIMER_CORE TIMER_EX1"
gmake -s clean_libs EXAMPLE="AWDG_Test IO_EX1 IO_EX1_STANDALONE_LOADER LIN_EX1 LIN_Unique_Loader_NAD PWM_EX1 TIMER_CORE TIMER_EX1"