@echo off

gmake -s clean PROFILE=80152-flash   SUBMODULE="IO_EX1 TIMER_CORE TIMER_EX1 TIMER_PWM_EX1" TARGET="example_$(PROFILE)"
gmake -s clean PROFILE=80152-otp-16K SUBMODULE="IO_EX1 TIMER_CORE TIMER_EX1 TIMER_PWM_EX1" TARGET="example_$(PROFILE)"


